puts 'seeding'
# Applicant.create(first_name: 'John', last_name: 'Johnnson', position: 'Taco Master', email: 'John@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 1)
# User.create(first_name: 'Todd', last_name: 'Toddson', title: 'owner', username: 'IAMTODD!')
# Note.create(applicant_id: 22, user_id: 6, body: 'This is a test note to test the note feature. Thank you!')
# Applicant.first.lists << List.create(name: 'Call List of Doom 2: Electric Boogaloo!!!!!', user_id: 6)
# Job.create(title: 'Cool Cat', description: 'Just be out there killin it', pay_rate: '30-45', location: 'Coolsville, Ohio', company: 'Cool Cats inc', user_id: 1)
# User.create(first_name: "Tucker", last_name: "Tuckson", title: "recruiter", username: "HiTodd,ImTucker")
# Job.create(title: 'Hitman', description: 'Just be out there killin it', pay_rate: '30-45', location: 'Coolsville, Ohio', company: 'Cool Cats inc', user_id: 6)
# Applicant.create(first_name: 'John', last_name: 'Johnnson', position: 'Taco Master', email: 'John@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnny', last_name: 'Johnnyson', position: 'Taco Master', email: 'Johnny@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johna', last_name: 'Johnanson', position: 'Taco Master', email: 'John@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johno', last_name: 'Johnnoson', position: 'Taco Master', email: 'Johno@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Job.create(title: 'Hitman', description: 'Just be out there killin it, in a very literal way. That is the exact description of this job... no more, no less.', pay_rate: '30-45', location
# Applicant.create(first_name: 'Johnq', last_name: 'Johnnson', position: 'Taco Master', email: 'John@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnnw', last_name: 'Johnnyson', position: 'Taco Master', email: 'Johnny@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johne', last_name: 'Johnanson', position: 'Taco Master', email: 'John@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnr', last_name: 'Johnnoson', position: 'Taco Master', email: 'Johno@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnt', last_name: 'Johnnson', position: 'Taco Master', email: 'John@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnnu', last_name: 'Johnnyson', position: 'Taco Master', email: 'Johnny@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johni', last_name: 'Johnanson', position: 'Taco Master', email: 'John@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnp', last_name: 'Johnnoson', position: 'Taco Master', email: 'Johno@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johns', last_name: 'Johnnson', position: 'Taco Master', email: 'John@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnnd', last_name: 'Johnnyson', position: 'Taco Master', email: 'Johnny@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnf', last_name: 'Johnanson', position: 'Taco Master', email: 'John@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johng', last_name: 'Johnnoson', position: 'Taco Master', email: 'Johno@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johhq', last_name: 'Johnnson', position: 'Taco Master', email: 'John@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnj', last_name: 'Johnnyson', position: 'Taco Master', email: 'Johnny@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnk', last_name: 'Johnanson', position: 'Taco Master', email: 'John@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnl', last_name: 'Johnnoson', position: 'Taco Master', email: 'Johno@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnz', last_name: 'Johnnson', position: 'Taco Master', email: 'John@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnnx', last_name: 'Johnnyson', position: 'Taco Master', email: 'Johnny@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnc', last_name: 'Johnanson', position: 'Taco Master', email: 'John@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
# Applicant.create(first_name: 'Johnv', last_name: 'Johnnoson', position: 'Taco Master', email: 'Johno@Johnmail.com', phone: 1234567890, city: 'Coolsville', state: 'Ohio', user_id: 6)
puts 'seeded'